# this file contains the various massages used in the program
# no code in this file will or should be executed, it is purely for human readability of the over-all program

# note that the actual message recived could have extra attributes due the being passed in various layers

# below is a client action query message
# it is generated by get_legal_moves, sent by run_game
query = {
    "channel_name": active_player.channel_name,
    'type': "action.query",
    "player_num": active_player.num,
    "q_type": "card_query_move",
    'options': [names, target],
}

# below is a response message to the above query
# it is sent by the client, reviced by response_handler, appended to dealersocket.response_list and
# finally processed by advance_state from within the run_game function

response = {
    'client_key': "query_response",
    'type': "query.response", # added by playersocket
    "player_num": active_player.num, # matches the query.player.num
    "q_type": "card_query_move", # subtype used in advance_state
    'choices': ['name','target']
}

# below is a admin command message sent from first client to dealer
msg = {
    'type':"admin.command",
    'subtype':"run.game",
    'arguments':"arguments"
}


# world state update object send from dealer socket to player socket and later to client
world_update = {
    'type':"msg.to.client",
    'client_key' : "lobby_update",
    'dealer_channel_name':"some channel name",
    'game_phase' : "lobby",
    'content': 'game or lobby json'
}
